/**
 * On-chain deposit watcher (TON network).
 *
 * Polls tonapi.io every WATCHER_INTERVAL_MS for incoming transactions to
 * TON_WALLET_ADDRESS and credits the matching pending intent in `transactions`.
 *
 * Handles BOTH:
 *   - Native TON transfers           → pending tx with currency='ton'
 *   - USDT Jetton (Tether) transfers → pending tx with currency='usdt'
 *
 * Matching contract: the on-chain memo (TON comment / Jetton forward-payload
 * text) MUST equal `transactions.referenceId`. Memos are generated by
 * /internal/{ton,usdt}-deposit-intent in the form  SKZ<userId>{T|U}<ts36>  so
 * they are unique per intent.
 *
 * Payment integrity: a memo match is necessary but NOT sufficient. The
 * received on-chain amount must be >= the intent's declared amount, otherwise
 * we refuse to credit and leave the intent pending for admin review. This
 * blocks an attacker from creating a 100-USDT intent, sending 0.01 USDT with
 * the same memo, and receiving the full SKZ.
 *
 * Idempotency: each credit pass runs an atomic
 *     UPDATE transactions SET status='completed' WHERE id=? AND status='pending'
 * inside a DB transaction together with the wallet increment. Two watcher
 * cycles, a manual admin credit, or a replayed chain event all converge on a
 * single credit because only the first wins the row update.
 *
 * Liveness under failure: events are added to the in-memory `seen` set ONLY
 * after every action in the event processes without throwing. A transient
 * DB / network blip leaves the event un-acked so the next cycle retries it.
 * Re-processing is safe because credit is idempotent (above).
 *
 * Known scale limit (TODO before high-volume launch): we only page the last
 * EVENTS_PAGE_SIZE events per cycle, no `before_lt` cursor. A sustained
 * inflow > 50 events / 30 s (or > ~50 events backlog after a tonapi outage)
 * can drop deposits. Add a persistent cursor and pagination loop when the
 * platform crosses ~10 deposits/min.
 *
 * Failure mode: tonapi outage / network error → cycle logged + skipped, no
 * partial state. Next cycle picks up where it left off (the chain doesn't
 * forget). Watcher boot is best-effort — if TON_WALLET_ADDRESS is unset it
 * stays disabled and the API still serves.
 */
import { db } from "@workspace/db";
import {
  transactionsTable,
  walletsTable,
  usersTable,
} from "@workspace/db";
import { and, eq, lt, sql } from "drizzle-orm";
import { logger } from "./logger";
import { notifyUser } from "./notify-user";

// Tether USDT₮ master address on TON mainnet (official). Stored in BOTH
// friendly (EQC…) form and the raw 0:hex form that tonapi returns inside
// JettonTransfer.jetton.address. We accept either because mismatched address
// encodings is the #1 reason on-chain matchers silently miss deposits.
const USDT_JETTON_MASTERS = new Set<string>([
  "EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs",                            // friendly bounceable
  "0:b113a994b5024a16719f69139328eb75959b0e2895f5902c8b1d46fecdc3621d",          // raw 0:hex
]);

const WATCHER_INTERVAL_MS = 30_000;
const TONAPI_BASE = "https://tonapi.io/v2";
const EVENTS_PAGE_SIZE = 100;      // bumped from 50 — handles ~2 min backlog at peak
const FETCH_TIMEOUT_MS = 10_000;
const INTENT_EXPIRY_HOURS = 24;    // abandon unpaid intents after 24 h
const CLEANUP_INTERVAL_MS = 30 * 60 * 1000; // run cleanup every 30 min

const NANO_TON = 1_000_000_000n;          // 1 TON  = 10^9 nanoton
const USDT_DECIMALS_DIV = 1_000_000n;     // USDT-Jetton uses 6 decimals

const log = logger.child({ component: "deposit-watcher" });

let started = false;
let intervalHandle: NodeJS.Timeout | null = null;
let cleanupHandle: NodeJS.Timeout | null = null;
const seenEventIds = new Set<string>();
const SEEN_CAP = 500;

/** Address aliases for our deposit wallet — populated at boot. tonapi
 *  returns recipient addresses in raw `0:hex` form, but operators configure
 *  the friendly UQ.../EQ... form. We resolve once via /accounts/{addr} and
 *  compare against either. */
const myAddressAliases = new Set<string>();

interface TonApiAction {
  type: string;
  status?: string;
  TonTransfer?: {
    sender:    { address: string };
    recipient: { address: string };
    amount: number; // nanoton, can be very large → JSON number loss possible
    comment?: string | null;
  };
  JettonTransfer?: {
    sender?:    { address: string } | null;
    recipient?: { address: string } | null;
    amount: string; // raw units as decimal string
    comment?: string | null;
    jetton: { address: string; decimals: number; symbol: string };
  };
}

interface TonApiEvent {
  event_id: string;
  timestamp: number;
  actions: TonApiAction[];
}

interface TonApiEventsResponse {
  events?: TonApiEvent[];
}

interface TonApiAccountResponse {
  address?: string;
}

/**
 * Look up the deposit address from env. Returns null if unset — disables the
 * watcher in dev/local without TON_WALLET_ADDRESS.
 */
function getDepositAddress(): string | null {
  const addr = (process.env.TON_WALLET_ADDRESS ?? process.env.TON_HOT_WALLET ?? "").trim();
  return addr.length > 0 ? addr : null;
}

function tonapiHeaders(): Record<string, string> {
  const headers: Record<string, string> = { Accept: "application/json" };
  // TONAPI_KEY (distinct from TON_API_KEY which is typically a toncenter key)
  // is the tonapi.io Bearer token from tonconsole.com. Sending the wrong key
  // returns 401, so we only attach when the dedicated env var is set.
  // Public tier (no key) allows ~1 req/sec, plenty for a 30s polling cycle.
  if (process.env.TONAPI_KEY) {
    headers.Authorization = `Bearer ${process.env.TONAPI_KEY}`;
  }
  return headers;
}

/**
 * Resolve a TON address via tonapi /accounts/{addr} to its canonical raw
 * `0:hex` form. Caller adds both the input and the resolved form to the
 * alias set so comparisons match regardless of encoding.
 */
async function resolveAddressAliases(input: string): Promise<void> {
  myAddressAliases.add(input);
  myAddressAliases.add(input.toLowerCase());
  try {
    const ctrl = new AbortController();
    const t = setTimeout(() => ctrl.abort(), FETCH_TIMEOUT_MS);
    const r = await fetch(
      `${TONAPI_BASE}/accounts/${encodeURIComponent(input)}`,
      { headers: tonapiHeaders(), signal: ctrl.signal },
    );
    clearTimeout(t);
    if (!r.ok) {
      log.warn({ status: r.status }, "address resolve non-OK; using input form only");
      return;
    }
    const body = (await r.json()) as TonApiAccountResponse;
    if (body.address) {
      myAddressAliases.add(body.address);
      myAddressAliases.add(body.address.toLowerCase());
      log.info({ raw: body.address }, "deposit address resolved");
    }
  } catch (err) {
    log.warn({ err: (err as Error).message }, "address resolve failed; using input form only");
  }
}

function isMyAddress(addr: string | undefined | null): boolean {
  if (!addr) return false;
  if (myAddressAliases.has(addr)) return true;
  return myAddressAliases.has(addr.toLowerCase());
}

async function fetchEvents(address: string): Promise<TonApiEvent[]> {
  const url = `${TONAPI_BASE}/accounts/${encodeURIComponent(address)}/events?limit=${EVENTS_PAGE_SIZE}`;
  const ctrl = new AbortController();
  const t = setTimeout(() => ctrl.abort(), FETCH_TIMEOUT_MS);
  try {
    const r = await fetch(url, { headers: tonapiHeaders(), signal: ctrl.signal });
    if (!r.ok) {
      log.warn({ status: r.status }, "tonapi events fetch non-OK");
      return [];
    }
    const body = (await r.json()) as TonApiEventsResponse;
    return Array.isArray(body.events) ? body.events : [];
  } catch (err) {
    log.warn({ err: (err as Error).message }, "tonapi events fetch failed");
    return [];
  } finally {
    clearTimeout(t);
  }
}

/**
 * Atomically credit a pending deposit intent.
 *
 * Returns true if THIS call performed the credit; false if the row was
 * already completed (idempotent no-op) or the wallet was missing.
 */
async function creditPendingIntent(
  pendingTxId: number,
  txHash: string,
  receivedRawAmount: string,
): Promise<{ credited: boolean; telegramId?: string; skzAmount?: string; newBalance?: string }> {
  try {
    return await db.transaction(async (tx) => {
      // 1. Atomic flip pending→completed. Only one watcher cycle wins.
      const [winner] = await tx
        .update(transactionsTable)
        .set({ status: "completed" })
        .where(and(
          eq(transactionsTable.id, pendingTxId),
          eq(transactionsTable.status, "pending"),
        ))
        .returning();
      if (!winner) return { credited: false }; // lost the race / already done

      // Patch metadata JSON with the chain proof — separate UPDATE so the
      // merge logic stays in JS where it can read the snapshotted row.
      let mergedMeta = winner.metadata ?? "{}";
      try {
        const parsed = JSON.parse(mergedMeta) as Record<string, unknown>;
        parsed.txHash = txHash;
        parsed.receivedRaw = receivedRawAmount;
        parsed.creditedAt = new Date().toISOString();
        mergedMeta = JSON.stringify(parsed);
      } catch {
        mergedMeta = JSON.stringify({ txHash, receivedRaw: receivedRawAmount });
      }
      await tx
        .update(transactionsTable)
        .set({ metadata: mergedMeta })
        .where(eq(transactionsTable.id, pendingTxId));

      // 2. Compute SKZ to credit from the intent's snapshotted expectedSkz —
      //    NEVER from the inbound chain amount, so a watcher bug or a
      //    sender shortfall can't conjure unexpected SKZ. (Underpayment is
      //    caught upstream in processAction before we ever reach here.)
      let expectedSkz = 0;
      try {
        const m = JSON.parse(winner.metadata ?? "{}") as { expectedSkz?: number | string };
        expectedSkz = parseFloat(String(m.expectedSkz ?? 0));
      } catch {
        expectedSkz = 0;
      }
      if (!Number.isFinite(expectedSkz) || expectedSkz <= 0) {
        log.error({ pendingTxId }, "intent has no expectedSkz metadata; refusing credit");
        throw new Error("INVALID_INTENT_METADATA");
      }

      // 3. Credit SKZ wallet atomically.
      const [w] = await tx
        .update(walletsTable)
        .set({
          balanceSkz:     sql`${walletsTable.balanceSkz}     + ${expectedSkz}`,
          totalEarnedSkz: sql`${walletsTable.totalEarnedSkz} + ${expectedSkz}`,
        })
        .where(eq(walletsTable.userId, winner.userId))
        .returning();
      if (!w) throw new Error("WALLET_NOT_FOUND");

      // 4. Look up telegramId for notification.
      const [u] = await tx
        .select({ telegramId: usersTable.telegramId })
        .from(usersTable)
        .where(eq(usersTable.id, winner.userId));

      return {
        credited: true,
        telegramId: u ? String(u.telegramId) : undefined,
        skzAmount: expectedSkz.toFixed(2),
        newBalance: w.balanceSkz,
      };
    });
  } catch (err) {
    log.error({ err: (err as Error).message, pendingTxId }, "creditPendingIntent failed");
    return { credited: false };
  }
}

/**
 * Process a single chain action. Looks up a matching pending intent by memo
 * and currency, validates the on-chain amount meets the intent, then credits.
 *
 * Throws on transient failure so the caller can leave the parent event
 * un-acked and retry next cycle.
 */
async function processAction(
  eventId: string,
  action: TonApiAction,
): Promise<void> {
  // ── Native TON transfer ──────────────────────────────────────────────────
  if (action.type === "TonTransfer" && action.TonTransfer) {
    const t = action.TonTransfer;
    if (!isMyAddress(t.recipient.address)) return;       // outgoing — ignore
    const memo = (t.comment ?? "").trim();
    if (!memo.startsWith("SKZ")) return;                 // not our memo

    const [intent] = await db
      .select()
      .from(transactionsTable)
      .where(and(
        eq(transactionsTable.referenceId, memo),
        eq(transactionsTable.currency, "ton"),
        eq(transactionsTable.status, "pending"),
        eq(transactionsTable.type, "deposit"),
      ));
    if (!intent) return; // unknown memo or already credited

    // Compute received TON with 4-decimal precision via fixed-point math.
    const nanoReceived = BigInt(Math.round(t.amount));
    const receivedTon = Number(nanoReceived * 10_000n / NANO_TON) / 10_000;
    const expectedTon = parseFloat(intent.amount);

    if (!Number.isFinite(expectedTon) || receivedTon + 1e-6 < expectedTon) {
      log.warn(
        { eventId, intentId: intent.id, receivedTon, expectedTon, memo },
        "TON deposit underpaid — refusing credit, leaving pending for admin",
      );
      return; // do NOT mark as seen; nothing to credit
    }

    const r = await creditPendingIntent(intent.id, eventId, receivedTon.toFixed(4));
    if (r.credited) {
      log.info({ eventId, intentId: intent.id, receivedTon, skz: r.skzAmount },
        "TON deposit credited");
      if (r.telegramId) {
        void notifyUser(
          r.telegramId,
          `✅ تم استلام إيداع TON\nالمبلغ: ${receivedTon.toFixed(4)} TON → ${r.skzAmount} SKZ\nالرصيد الجديد: ${r.newBalance} SKZ`,
        );
      }
    }
    return;
  }

  // ── USDT-Jetton transfer on TON ──────────────────────────────────────────
  if (action.type === "JettonTransfer" && action.JettonTransfer) {
    const j = action.JettonTransfer;
    const jettonAddr = j.jetton.address;
    if (!USDT_JETTON_MASTERS.has(jettonAddr) && !USDT_JETTON_MASTERS.has(jettonAddr.toLowerCase())) {
      return; // other jetton (some scam tokens copy comments) — ignore
    }
    if (!isMyAddress(j.recipient?.address)) return;       // outgoing — ignore
    const memo = (j.comment ?? "").trim();
    if (!memo.startsWith("SKZ")) return;

    const [intent] = await db
      .select()
      .from(transactionsTable)
      .where(and(
        eq(transactionsTable.referenceId, memo),
        eq(transactionsTable.currency, "usdt"),
        eq(transactionsTable.status, "pending"),
        eq(transactionsTable.type, "deposit"),
      ));
    if (!intent) return;

    let receivedUsdt = 0;
    try {
      const raw = BigInt(j.amount);
      receivedUsdt = Number(raw * 100n / USDT_DECIMALS_DIV) / 100;
    } catch {
      log.error({ eventId, intentId: intent.id, amount: j.amount }, "JettonTransfer.amount unparseable");
      return;
    }
    const expectedUsdt = parseFloat(intent.amount);

    if (!Number.isFinite(expectedUsdt) || receivedUsdt + 1e-4 < expectedUsdt) {
      log.warn(
        { eventId, intentId: intent.id, receivedUsdt, expectedUsdt, memo },
        "USDT deposit underpaid — refusing credit, leaving pending for admin",
      );
      return;
    }

    const r = await creditPendingIntent(intent.id, eventId, receivedUsdt.toFixed(2));
    if (r.credited) {
      log.info({ eventId, intentId: intent.id, receivedUsdt, skz: r.skzAmount },
        "USDT-Jetton deposit credited");
      if (r.telegramId) {
        void notifyUser(
          r.telegramId,
          `✅ تم استلام إيداع USDT\nالمبلغ: ${receivedUsdt.toFixed(2)} USDT → ${r.skzAmount} SKZ\nالرصيد الجديد: ${r.newBalance} SKZ`,
        );
      }
    }
  }
}

async function tick(address: string): Promise<void> {
  const events = await fetchEvents(address);
  for (const ev of events) {
    if (seenEventIds.has(ev.event_id)) continue;
    let allActionsOk = true;
    for (const action of ev.actions ?? []) {
      try {
        await processAction(ev.event_id, action);
      } catch (err) {
        allActionsOk = false;
        log.error({ err: (err as Error).message, eventId: ev.event_id },
          "processAction threw — leaving event un-acked for retry");
      }
    }
    // Only mark seen once ALL actions in the event processed without
    // throwing. A transient DB/network blip leaves the event un-acked so
    // the next 30s cycle retries; credit-side idempotency (atomic UPDATE
    // WHERE status='pending') guarantees no double-credit on retry.
    if (allActionsOk) {
      seenEventIds.add(ev.event_id);
      if (seenEventIds.size > SEEN_CAP) {
        const trim = seenEventIds.size - SEEN_CAP;
        let i = 0;
        for (const k of seenEventIds) {
          if (i++ >= trim) break;
          seenEventIds.delete(k);
        }
      }
    }
  }
}

/**
 * Cancel unpaid deposit intents older than INTENT_EXPIRY_HOURS.
 * Prevents table bloat from abandoned invoices (user opened intent, never paid).
 * Safe to run alongside the credit watcher — atomic UPDATE WHERE status='pending'
 * means a concurrent credit event always wins (its UPDATE lands first, leaving
 * status='completed', so this cleanup skips it on next run).
 */
async function expireOldPendingIntents(): Promise<void> {
  try {
    const cutoff = new Date(Date.now() - INTENT_EXPIRY_HOURS * 3600 * 1000);
    const expired = await db
      .update(transactionsTable)
      .set({ status: "cancelled" })
      .where(
        and(
          eq(transactionsTable.status, "pending"),
          eq(transactionsTable.type, "deposit"),
          lt(transactionsTable.createdAt, cutoff),
        ),
      )
      .returning({ id: transactionsTable.id });
    if (expired.length > 0) {
      log.info({ count: expired.length }, "expired old pending deposit intents");
    }
  } catch (err) {
    log.error({ err: (err as Error).message }, "intent expiry job failed");
  }
}

export function startDepositWatcher(): void {
  if (started) return;
  const address = getDepositAddress();
  if (!address) {
    log.info("TON_WALLET_ADDRESS not set — deposit watcher disabled");
    return;
  }
  started = true;
  log.info({ address, intervalMs: WATCHER_INTERVAL_MS }, "deposit watcher started");

  // Resolve the address to its raw 0:hex form so we can match tonapi's
  // canonical recipient encoding. Fire-and-forget — if it fails the watcher
  // still works (falls back to input-form matching).
  void resolveAddressAliases(address);

  // Kick a first cycle immediately so a fresh boot doesn't wait 30s.
  void tick(address).catch((err) => log.error({ err }, "initial tick failed"));
  intervalHandle = setInterval(() => {
    const a = getDepositAddress();
    if (!a) return;
    void tick(a).catch((err) => log.error({ err }, "tick failed"));
  }, WATCHER_INTERVAL_MS);
  intervalHandle.unref?.();

  // Kick the expiry cleanup immediately (clears any backlog from downtime),
  // then run on a 30-minute schedule.
  void expireOldPendingIntents();
  cleanupHandle = setInterval(() => {
    void expireOldPendingIntents();
  }, CLEANUP_INTERVAL_MS);
  cleanupHandle.unref?.();
}

export function stopDepositWatcher(): void {
  if (intervalHandle) clearInterval(intervalHandle);
  if (cleanupHandle)  clearInterval(cleanupHandle);
  intervalHandle = null;
  cleanupHandle  = null;
  started = false;
  myAddressAliases.clear();
  seenEventIds.clear();
}
