export interface GameConfig {
  id: string;
  emoji: string;
  nameAr: string;
  theme: string;
  mechanic: string;
  price: number;
  maxPrize: number;
  gradientFrom: string;
  gradientTo: string;
  accentColor: string;
  gridSize: number;
  symbols: string[];
}

export const GAMES: GameConfig[] = [
  {
    id: "tribe-treasure",
    emoji: "💎",
    nameAr: "كنز القبيلة",
    theme: "صحراء / ذهب",
    mechanic: "3×3 — طابق 3 رموز",
    price: 50,
    maxPrize: 5000,
    gradientFrom: "#92400e",
    gradientTo: "#b45309",
    accentColor: "#f59e0b",
    gridSize: 9,
    symbols: ["💎", "🏺", "🌵", "🐪", "🌙", "⭐", "🔮", "💛", "🦅"],
  },
  {
    id: "luck-garden",
    emoji: "🍀",
    nameAr: "بستان الحظ",
    theme: "فواكه / خضراء",
    mechanic: "5 مربعات — طابق الفاكهة",
    price: 30,
    maxPrize: 3000,
    gradientFrom: "#14532d",
    gradientTo: "#166534",
    accentColor: "#22c55e",
    gridSize: 5,
    symbols: ["🍀", "🍇", "🍓", "🍋", "🍊", "🍉", "🌿", "🌸", "🍑"],
  },
  {
    id: "eastern-nights",
    emoji: "🌙",
    nameAr: "ليالي الشرق",
    theme: "عربي / أزرق",
    mechanic: "4 خانات — اكشف العملة",
    price: 40,
    maxPrize: 4000,
    gradientFrom: "#1e1b4b",
    gradientTo: "#3730a3",
    accentColor: "#818cf8",
    gridSize: 4,
    symbols: ["🌙", "⭐", "🕌", "🪔", "🌟", "💫", "🔮", "🌺", "🏮"],
  },
  {
    id: "wealth-lightning",
    emoji: "⚡",
    nameAr: "صاعقة الثروة",
    theme: "كهرباء / بنفسجي",
    mechanic: "3 خانات — البرق الثلاثي",
    price: 60,
    maxPrize: 6000,
    gradientFrom: "#4c1d95",
    gradientTo: "#6d28d9",
    accentColor: "#a78bfa",
    gridSize: 3,
    symbols: ["⚡", "🌩️", "💜", "🔋", "💡", "🌪️", "🔆", "✨", "🫧"],
  },
  {
    id: "golden-dragon",
    emoji: "🐉",
    nameAr: "تنين الذهب",
    theme: "تنين / أحمر",
    mechanic: "رقم × معامل — اضرب الدرج",
    price: 100,
    maxPrize: 10000,
    gradientFrom: "#7f1d1d",
    gradientTo: "#991b1b",
    accentColor: "#ef4444",
    gridSize: 6,
    symbols: ["🐉", "🔥", "💰", "👑", "🎖️", "🏅", "💎", "🌋", "⚔️"],
  },
  {
    id: "luck-wave",
    emoji: "🌊",
    nameAr: "موجة الحظ",
    theme: "بحر / تيل",
    mechanic: "6 مربعات موج — 3 في صف",
    price: 45,
    maxPrize: 4500,
    gradientFrom: "#134e4a",
    gradientTo: "#0f766e",
    accentColor: "#2dd4bf",
    gridSize: 6,
    symbols: ["🌊", "🐚", "🐠", "🐬", "🏄", "🦀", "⚓", "🐙", "🌈"],
  },
  {
    id: "jungle-king",
    emoji: "🦁",
    nameAr: "ملك الغابة",
    theme: "سافاري / برتقالي",
    mechanic: "اكشف الحيوان × نقاطه",
    price: 55,
    maxPrize: 5500,
    gradientFrom: "#7c2d12",
    gradientTo: "#c2410c",
    accentColor: "#fb923c",
    gridSize: 6,
    symbols: ["🦁", "🐘", "🦒", "🐆", "🦏", "🦓", "🦅", "🌴", "🍃"],
  },
  {
    id: "wealth-mask",
    emoji: "🎭",
    nameAr: "قناع الثروة",
    theme: "مسرح / وردي",
    mechanic: "زوّج الأقنعة",
    price: 35,
    maxPrize: 3500,
    gradientFrom: "#831843",
    gradientTo: "#9d174d",
    accentColor: "#f472b6",
    gridSize: 6,
    symbols: ["🎭", "🎪", "🎨", "🎬", "🎠", "🎡", "🌹", "🎀", "✨"],
  },
  {
    id: "space-journey",
    emoji: "🚀",
    nameAr: "رحلة الفضاء",
    theme: "فضاء / بنفسجي داكن",
    mechanic: "3 كواكب — طابقها",
    price: 80,
    maxPrize: 8000,
    gradientFrom: "#0f0f2e",
    gradientTo: "#1e1b4b",
    accentColor: "#c084fc",
    gridSize: 3,
    symbols: ["🚀", "🪐", "⭐", "🌌", "🛸", "🌙", "☄️", "🌟", "👾"],
  },
  {
    id: "champions-cup",
    emoji: "🏆",
    nameAr: "كأس الأبطال",
    theme: "ذهبي / بريق",
    mechanic: "كأس مخفي — ماذا بداخله؟",
    price: 150,
    maxPrize: 15000,
    gradientFrom: "#713f12",
    gradientTo: "#92400e",
    accentColor: "#fcd34d",
    gridSize: 5,
    symbols: ["🏆", "🥇", "🎖️", "👑", "💎", "⭐", "🌟", "🎯", "🔑"],
  },
];
